name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    environment:
      name: Niedernhausen
      url: "https://app.cachix.org/deploy/workspace/aqube"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "extra-platforms = aarch64-linux"
      - uses: docker/setup-qemu-action@v3                                    
      - uses: cachix/cachix-action@v14
        with:
          name: aqube
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@v5
      - run: nix flake check -Lvv
        name: "Check flake syntax"
      - run: nix build --print-build-logs .#cachix-deploy-spec
        name: "nix build"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          cachix push aqube ./result
          cachix deploy activate --async ./result
