---
name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # *     *     *   *    *        command to be executed
    # -     -     -   -    -
    # |     |     |   |    |
    # |     |     |   |    +----- day of the week (0 - 6) (Sunday=0)
    # |     |     |   +------- month (1 - 12)
    # |     |     +--------- day of the month (1 - 31)
    # |     +----------- hour (0 - 23)
    # +------------- min (0 - 59)
    - cron: "0 2 * * 1" # runs every Monday at 02:00
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          pr-assignees: azerbe
